### ISSUE TITLE
Add repository info to "templates" command

### ISSUE THREAD

**Issue by zstumgoren** [associatedpress/datakit-project#20]
Update the `templates` command to display detailed version control information about locally installed templates. This should include:

- commit SHA
- commit subject
- short commit date

### Tasks

- [x] Determine git log invocation to provide short, informative message on latest local commit: `git log -n 1 --pretty=format:"%h %s (%cd)" --date=short`
- [x] Refactor commands into proper directory similar to datakit-data
- [x] Move shared test fixtures conftest.py similar to datakit-data
- [x] Create a `Cookiecutters` wrapper to encapsulate template-related functionality
- [x] Add `Cookiecutters.list` method and refactor `templates` command
- [x] Update test coverage for `templates` to monkeypatch of subprocess call to git log and to verify that listed templates include repo details

## Implementation notes

Before implementing, should do a more thorough review of Cookiecutter source for possibly useful code to lean on. If we have to roll our own, here are two alternatives:

* Create a `repo_info` function or similar modeled on Cookiecutter's [clone](https://github.com/audreyr/cookiecutter/blob/3bc7b987e4ae9dcee996ae0b00375c1325b8d866/cookiecutter/vcs.py#L59). Specifically, we can perform a subprocess call to appropriate git commands to fetch information about the remote repo.
* Look into python client libraries that interoperate with git, though we should be careful about adding new, heavy dependencies.
